FROM rocm/pytorch:latest


RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8
RUN update-locale
RUN apt-get update && apt-get install -y tesseract-ocr mkvtoolnix 

RUN apt-get install -y wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \ 
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get -y install google-chrome-stable

RUN pip install --upgrade pip

ENV FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"
RUN . /opt/venv/bin/activate
RUN git clone https://github.com/ROCm/flash-attention.git &&\ 
    cd flash-attention &&\
    FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE" pip install --no-build-isolation .

RUN git clone https://github.com/leuchthelp/sup-convert.git
WORKDIR /sup-convert
RUN pip install -r requirements.txt